FROM gitpod/workspace-full

FROM nvidia/cuda:10.1-devel

RUN apt-get update && apt-get install -y \
        bc \
        git \
        wget \
        ccache \
        python3 \
        python3-distutils \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN brew install cmake

ARG NPROC=8

# Clone Kokkos fork of the LLVM Project and build Clang
ENV LLVM_DIR=/opt/llvm
RUN LLVM_VERSION=55b3bcf643685c63fcc529d434bed112fdf03939 && \
    LLVM_URL=https://github.com/kokkos/llvm-project/archive/${LLVM_VERSION}.tar.gz &&\
    LLVM_ARCHIVE=llvm.tar.xz && \
    SCRATCH_DIR=/scratch && mkdir -p ${SCRATCH_DIR} && cd ${SCRATCH_DIR} && \
    wget --quiet ${LLVM_URL} --output-document=${LLVM_ARCHIVE} && \
    mkdir llvm-project && \
    tar -xf ${LLVM_ARCHIVE} -C llvm-project --strip-components=1 && \
    cd llvm-project && \
    mkdir build && cd build && \
    cmake \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=$LLVM_DIR \
      -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;compiler-rt" \
    ../llvm && \
    make -j${NPROC} && \
    make install && \
    echo "${LLVM_DIR}/lib" > /etc/ld.so.conf.d/llvm.conf && ldconfig && \
    rm -rf ${SCRATCH_DIR}
ENV PATH=${LLVM_DIR}/bin:$PATH

